---
### Drone configuration file for gotosocial-drone-build
### Connects to https://drone.superseriousbusiness.org to perform testing, linting, and automatic builds/pushes to docker.
###
### For documentation on drone, see: https://docs.drone.io/
### For documentation on drone docker pipelines in particular: https://docs.drone.io/pipeline/docker/overview/

kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    username: gotosocial
    password:
      from_secret: gts_docker_password
    repo: superseriousbusiness/gotosocial-drone-build
    tags:
    - latest 
    - "0.3.0"
    build_args:
    - GORELEASER_VERSION=v1.20.0
    - GO_SWAGGER_VERSION=v0.30.4
    - JD_VERSION=v1.7.1
    - MINIO_MC_VERSION=RELEASE.2023-08-08T17-23-59Z
    - DOCKER_BUILDX_VERSION=v0.11.2
    - GO_CONTAINER_VERSION=1.21.0-alpine
  when:
    event:
      include:
      - push
    branch:
      include:
      - main

trigger:
  repo:
    exclude:
    - "*"
    include:
    - superseriousbusiness/gotosocial-drone-build

---
kind: signature
hmac: dc6e92d19422fd6f24505addc7e78b877d2e053d8d9ea397f33821a03cd58477

...
